@startuml

DVP : (1) to receive the Payment-Order-Token (POT)
DVP : (2) transfer the Asset Token(s) (AT) from the wallet of the seller to itself
DVP : (3) initiate the payment promised by the POT
DVP : (4) after receiving the confirmation of payment, send the AT to the wallet of the buyer.
DVP : transfer AT from seller
DVP : wait for increase of allowance in seller
DVP : deactivate POT

ERC721 <|-- POT

POT : The type of AT
POT : number of AT
POT : the wallet address of the seller
POT : the wallet address of the buyer
POT : deactivation by DvP
POT : deactivation by DvP
POT : Owner [address]
POT : Amount
POT : Currency
POT : Sender [address]
POT : Receiver [address]
POT : status [issued, Payment initiated, Payment confirmed, deactivated]
POT : dealDetailNum
POT : dealDetailNum2
POT : dealDetailAddress [address]
POT : mintTime [time]

POT_SC : issuePaymentToken
POT_SC : initiatePayment
POT_SC : confirmPayment
POT_SC : deactivatePot

ERC20 <|-- AT_SC

AT_SC : deactivatePot

Seller : grant allowance for AT transfer to DVP
Seller : get AT back from DvP (manual by DvP Manager)

DvP_Manager : checkDeliveryForPot
DvP_Manager : executeDelivery
DvP_Manager : deactivateOldPot
DvP_Manager : cancelSettlement

Pausable <|-- DVP_SC

@enduml
